/**
null_awe

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQ@EZSPZUY6TTLTwdpUPZ%XNWQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW@NN@X%UCwYTIi",`-:_;"/\i?[Iouu5nLT6YFPm@QMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQN%CL5uu5LLwRQQWKRN%%%mXOONN@@DDDDDD@@@DDR&WKD@N%Z%%ON@QMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQNhuIIu6ZX@RKRD@@@NNNNNNNNNNNNNNNOOOOXXXXXXXXOONN@DRKKWWWWW@N@NO@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQETIfuUXDWW&D@@@@@@@NNNNNNNNNNNNNNNNNNNNNNNNNNNNN@@@@@DDRRRRRR&R&KWDZYTU@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWUJjuP@QQKRRDDRRRRRRRDDDRDDDDDD@@@@@@@@@@@@@@DDDDDDRRRRRRRRRDRRRRRRRRRR&QRZ5I5ZQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQPJjLXQQWK&RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDDRDRRRRRRRRRRRWQQmnleSQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMXo?5EQQWKRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDRDRRRDDDDDDDDDDDDDDDDDDDDDRRWQQEo|oOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWYjePKQWKRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDRKWQ@L/iqQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM@5rLNQWWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDRWQRYi"u@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMmj]%QWW&RRRRRRRRDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD@DDD@@@@@@@@DDDDD&WQNo_\8QMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMSz%QWKRRRRRRRRRRRRRRRRDRRRRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDDD@@@@@@@@@@@@@@@@D@@@@@@@@@@@@@@@@@@@@@@@DRKWNy:\NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM@x2QW&RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDD@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NN@@@@@@@@@DRKm[-yRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMQk?ZW&RRRRRRRRRRRRRRRRRRRRRRRDDRRRRRRRRRRRRDDDDDDD@@@@@@@D@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNNNNNN@@@@@@@@@DDDL""SMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMM@}nDW&RRRRRRRRRRRRRDRDDDRRRRDDDDDDDRRRDDDDDDDDDDDD@@@WK@@@@@@@NN@@@NN@@NN@NN@@@@@@@@@@@@@@NN@NNNNNNNN@@@@@@@@@@@Xf,oQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMS}mWRRDDRRRRRRRRDDDDDDDDDDRDDDDDDDDDDDDDDDDDDD@@@@@@@Q&QR@@@@@NNNNNNNNNNNNNNNNN@@@@@@@@@@@@@NNN@NNNNNNNN@@@@@@@@@@@g~\mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMTnDRDDDDDDRRRRRDDDRDDDDDDDD@DDDDDDDDDDDDDDDD@@@@@@@N@QN$DQ@@@@NNNNNNNNNNNNNNNNNNNNNNNNNNNNN@NNNNNNNNNNNNONN@@@@@@@NNN%j_TMMMMMMMMMQEQMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMT8RDDDDDDDRRRRRDDDDDDDDDDDD@DDDDDDDDDDDDDD@@@@@@NDDNDQXhqNM@@@NNNNNNNNNNNNNNNNOONNNNNNNNNNNNNNNNNNONNONNNNOON@@@@@@@NNNNC/aQMMMMMMMmC@MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMbSRDDDDDDDDRDDDDDDDDDDDDDDD@@DDD@DDD@@@DD@@@@@@@NDKNWQ%YYYXM@@NNNNNNNNNNNNNNNNOOOOOONNNNNOOOOONNNNOOXNNXONNOOOXN@DD@@@NNNNXcjKMMMMM@pF%MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMqhD@@@D@@DDRRDDDDDDDDDDDDDD@@@@@@@@@@@@@@@@@@@@NN@Q@RRPYqqYOMDNNNNNNNNNNNNOOOOOOOOOOOOOOOOOOOXOOOOOOOXXONXOOOOOOXO@RR@@@NNOON5r@MMMRUF$8RMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMM8a@@@@@@@@@@&DDDDDDDDDDDDDD@@@@@@@@@@@@@@@@@@@NNNNWWQ@TdCCCh@M@NNNOOONNNNNOOOOOOOOXOOXOOXXXXXXOXXOOXXXXXXONXOOOOOOXXNRWD@@NNNNNZlPMNCCUSSNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM@|ZN@@@@@@@@@R@@@@@@D@@@@@@@@@@@@@@@@NN@@@@@NNNNNNRQQ%2L6YCCqRQ@NOOOOONNOOOOOOOOOOOOXOXOOOOXXXOXXXXXXXXXXXXONXOOOOOOOONDW@@@NNNOONOX5nL6CF%MMMMMMMMMMMMMMMMMMMMM
MMMMMMMMo}%mONNN@N@ND@@@@@@@@@@@@@@NNN@@@@@@NNNN@NNNNNNNO@QWLve5LThYUQQNOOOOOONOOOOOOOOOOOOOOOOOOOOOXXXXOOOXOOOXOOXXNOOOOOOOOOONRW@@@NNNNWNaxaounLSMMMMMMMMMMMMMMMMMMMMM
MMMMMMM@!kSPSP%%mXNNDON@@@@@@@@@@@NNNNNNNNNNNNNNNNNNNNOONQZi~|sIu5LLZMDNOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXOOOOOOOOOOOONNNNNN@KW@NNN@QP|\rl[xayYMMMMMMMMMMMMMMMMMMMMM
MMMMMMMTiZSPPPPSSSX@NZNN@@NNN@NNNNNNNNNNNNNNNNNNNNNOOOXNNI__"!il[xaoXQNOOOOOOOOOOOOOOOOOOOOOOOXOOOOOOOOOOXXONNNNNOXXmOXXE%%%%%ZSmDWQDmPNo:_"/|tvclSMMMMMMMMMMMMMMMMMMMMM
MMMMMMM[J%PZPZPPS%N@mPPZ%EmmmmONNOONNNNNNNNOOONNNNOOOOX%|-:;"~!|t?jnQ@NNNNNNNOOOOOOOXXmmEE%%mOON%ZZZZZPPSXXOZU$gFCqY6UOOPhYYYYYYpNDRY5ruj`_;;~!\\i@MMMMMMMMMMMMMMMMMMMMM
MMMMMMD!LZPPPPPSSmN@ZZZPPPPPPPXNN%ZZZZ%%%XmXEE%XOOOOOOXn`-,_;"~/!!tOKZZZZZZ%OXOZ88$FpCqqh666POONPhddddddd%OO%qCCCqCCC6ZNOPYYYYqqhZ@Rd;""L/:__;;""LMMMMMMMMMMMMMMMMMMMMMM
MMMMMMN~LSSSSPPSZONXZPPPPPSSP%NNOZ%%Z%%ZZXX%ZZ%OOOOXXXXJ```':_;;;~UQ%g8UU8$UOOOZCpppCqqYYYYhFONN%dYYhdhhhSNONPCppCCCpC6%NOUqqqYYhYNDDj;;|L,:____!@MMMMMMMMMMMMMMMMMMMMMM
MMMMMME~FNOmmEE%EON%ZZZPPPPPPENNEZZ%%%EEmOOOOOOOOOOOXmm?'`..`'--;gW%p$8SUU88mOX%CppCCqYYYhh6b%ONXYddhd6666%ONEYYqCqqpFqhmNECqYYhhbZRKZ";:Lt`:___bMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMP\ZNNNNNOOOOXXNNNNNNNNNNONNNNNNOOOOOOOOOOOONNXXmZ;.......!EQN%%ZZ%%ZZPEOXESSUSUU8gpCh6LZONNCkkkkwwTTUNNN8YYYCgS%%TUNNZSSSPPUqNRKpu/jL  ..lQMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMYimNOOOOOOONNNNNNOOOOOOONNONNONOOOOOOOOOOONNNOXm6. ...  !@RNXOONNNNOOXXNOXONNNNNNNNNNOZSNNNEEEmmmmEE%m@NOXONNNNNNOZO@NNNNNNNCZRWQQd!P;  "NMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMML}@NOOOOOOO@ZNRD@@NNOOOONNNNNNNOOOOOOOOOONN@OOXNu     !SWNOONN@@NONNOOX@NXONNNNNNNNNNNNONNNNNNNNNNNNNm@@N@@@@@@@@@@N@@OOONNNNmDWQQNiLa |NR@WMMMMMMMMMMMMMMMMMMMMMM
MMMMMM5L&NNNOOOON@PkbTTqPm@RR@@NNNNNNNNOOOOOOONO@@XXXDp.-!fUQQRN%PUCTnLYNNNOXDNOONNN@@@@@@@NNNN@NNNNNNNNNNNXRD@@@@@@@@@@@@@&NNNNNNNN@WWQDIf%wD@@@OMMMMMMMMMMMMMMMMMMMMMM
MMMMMMoFRNNOOOOX@NN@DNZdL55LTUW@NNNNNNNNNOOOONNNRNXXNWQ@WQQRXCyrjoTZNDR@NNOOX&@ON@@@@@@@@@@@@@N@@NNN@@@@@@@O@W@DDDDDDDDDDD@WR@@@@@@@@KWWKLj@WR@@RgRMMMMMMMMMMMMMMMMMMMMM
MMMMMMoZDNNOOOOXDNNNNNN@@DD@NNWNNNNNNNNNNNNNNNNNKOXNNQQMDnunT8%NRRD@@NNNNNNOORQNN@D@@DDD@@@@@@@@@@@@@DDD@@@NNQKDDDDDDDDDDDD&QD@DDDDD@RWWWSvmWD@DWP%MMMMMMMMMMMMMMMMMMMMM
MMMMMMuODNNOOOONRNNNNNNNNNNNNDRNNNNNNNNNNNNND@X@RXON@QQQDmKQQR@@@@@@@@@@@NNNNDMD@DDDDDDDDDDDD@@DD@@DDDDDDDD@OQQDDDDDDDDDDDDRQ&DDDDDD@RWWWm]8WRDRWXCMMMMMMMMMMMMMMMMMMMMM
MMMMMMLDDNOOOOO@D@@@@@NNNNNNNW@NNNNNNNNNNNNDKNODDXON@QDNN@DQR@@@@@@@@@@@@@@NN@MQ@DDDDDDDDDDDDD@DDDDDDDDDDDD@%QQRDDDDDDDDDDDDQWDDDDDR@DQWWN5wWRRRW@TMMMMMMMMMMMMMMMMMMMMM
MMMMMMqWRNNOOOO@@R@@@@@@@@@@DQR@NNNNN@@@@@DQ@NN&@XNNRQIymNDWK@@DDDDD@D@D@@@@@@MQDDDDDDDDDDDDDDDDDDDDDDDDDDD@ZQQRDDDDDDRRRRDRQWDDDDDRD@WWW@wLWKRRW&LMMMMMMMMMMMMMMMMMMMMM
MMMMMMPQKNNNNOND@KWDD@@@@@@@X5ZD&@NN@@@@@@QR@NNW@XONWL'iO@DKWDDDDDDDDDDDDD@@@DMMRDDDDDDDDDDDDDDDDDDDDDDDDDD@SWQDDDDDRRRRRRDRQWDDDDDD@NWKW@$L&KRRKQnMMMMMMMMMMMMMMMMMMMMM
MMMMMM%QW@NNNO@RDRQRDDD@@@@@WNdunEWWD@@D&QQKRRRQ@XON@/,;%N@DW@DDDDDD@@@@D@@@@RMMRDDD@@@D@@@@@@@@@@@DDDDDDDDNbOD@@@@DDDDDDDDRQKDDDDDDNOK&WDSLDK&RRQnMMMMMMMMMMMMMMMMMMMMM
MMMMMMOQWDNNNNRRDRQWDDDDDDDDQQMQNjvTm@@@@@NOOO@QNmN@O":.L@@@W@@@@@@@@@@@@@@@NDWQ@NNNNN@@@NNNNNNNNNNNN@@@@@NX6S%NNN@@@@@@@@@RQD@@@@@@mORRK@P6RKRRRWuMMMMMMMMMMMMMMMMMMMMM
MMMMMMDWWK@NN@RRRRQQRRDDDDDbnLLL5ooIl\|n%ONOON@QNEN@E~'.r&@@RDN@@NNNNNNNNNNNNR@R@NNNNNNNNNNNNNNOONNNNNNNNNO%YLmONNNNNNNNNNNWQNNNNNNN%NKRK@Z%WKRRRRJMMMMMMMMMMMMMMMMMMMMM
MMMMMMQWKKR@@RRRRRQQRDDDDDWQQQQWWWQQQWOwuSQMMMMQNmN@%;ing@@@DDNNNNNOOOOOOXXXmD$DNXXXXXXmmXXXXmN@EmmmmmXXmmEZTPDmmXXXXXXXXXNQDmXXXXXmZ@WKKNZ@QWRRRRfQMMMMMMMMMMMMMMMMMMMM
MMMMMMQRK&RDDRRRRRMQRDDDDDO@RQQQWWWQQQQQDPoTWQLE@mN@%;;:.[K@DKOOOXXXmmmmmmmEOZ;mNE%%%%%%%%%%%mWO%%%%%%%%%%ZEZ%N%%%%%%%%%%%@QN%EEEEE%Z@QKKN%DQWRRRR}QMMMMMMMMMMMMMMMMMMMM
MMMMMMMRRRRDDRRRRRMQRRRDDDEUT5IynFmRQMMQQQQQ@v CDEN@Z`   '%DN&OmEEEEEEEE%%%%NI\@X%%%%%%%%%%%Z@@%%%%%%%ZZZZZn!OX%ZZ%%%%%%%EW@%%%%%%%ZZURW&OZRQWRRRR}QMMMMMMMMMMMMMMMMMMMM
MMMMMMM&RRRRRRRRRKMQRRRDDRQQQWRN%S6LnnLLFRWL_  CD%O@Z.    n&L6%ZZZZ%Z%ZZZ%%EN|e&OE%%%%%%ZZ%m%pEE%%%%%%%%%ZP!5DE%EEE%EEEmEE%%%%%%%%%%maEW&X%WQW&&&&fMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWRRRRRRRRRKMQRRRDDKQQQQMMMMMMMWD@RE"    FR%NDNvjeun%MQQQQQQQQQQW@ZnJo2~ioJIJIxf}[jjj\:`\|\!!///////; "o8L5I[vfF%EXN@KR@%Yu}j?i\NQWmEQQWKKKWaMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWRRRRRRRRRKMQRRDD&QQDmZSSZE@MMMMWf.     qK%NRMMMMMMMMMMMMMMMMMMMMMWZJ~.     ..........      ......   `J_ ./yZWMMMMMMMMMMMQNZTnp@QWmXQQWKKWWuMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWRRRRRRRR&KQQDDD&QS!.      .~oZWb       gDEODMMMMMMMMMMMMMMMMMMMMMMMMWZf:   ........................ .:/umQMMMMMMMMMMMMMMMMMMLiNQWmNQQWKKWQnMMMMMMMMMMMMMMMMMMMMM
MMMMMMMQRRRRRRR&&KQQRDRQC.      .     _z|.-~iIhR@XX@MMM&%6ZQDNX%ZZPZEXXNDQMQQQ&Oy`  ......................  ~6@WQMQRNOm%%%NRQZ2P@MMMM@WQKmNQWK&KWQTMMMMMMMMMMMMMMMMMMMMM
MMMMMMMQRRRR@DK&RWQQRWWW?     :~;"";,.  ..cuLTq@DNXNKu!,.|RKNNOOOOmwzP%E%E@QR@QKDk, ...................... |%@@R@mZZSfeF%N@KWN. .iDMMWQQKX@QW&&KWQ6MMMMMMMMMMMMMMMMMMMMM
MMMMMMMQRRRDWQQKNNDD@QQRr    _!.:/!!!~_.       5RNOOX;:,.TMD@N@@@@NOmON@DRRW@|rn%No...................... ;SZ$@@NONNN%%X@@Z5Ju". _@QDWQQKO@QWRR&QQCMMMMMMMMMMMMMMMMMMMMM
MMMMMMMQDDDD@O?-../o%K@@5    :.:/!!!!!"..      lK@@NN/.. wMD@X%gYgXNmZSFor"_!;.. _r_..................... !~.pD@NmZ%XNNpi.   :.. IDLpQWQRNRQ&RR&QWFMMMMMMMMMMMMMMMMMMMMM
MMMMMMMQDRDD@P.  ~LNOmKNZ!     ;~/!!!".....    \K@@@@i   }M%LuoyJ6RW&b\v"_:_\; `_` ......................   `ENSLaeLNWN5[[}e5X_ .ur/DKRQDNKQRR&&QDSMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWDRRD@N\.}@PItioXDP"    '~!!!!~` ....   :NRD@@j   -m%euuuaT@RX622nnLPD]     ......................    C%uoyyn%@Soaao5m$   ..6Q@DWDNWQDRR&Q@%MMMMMMMMMMMMMMMMMMMMM
MMMMMMMNDRDD@@uaNuiiiiirnNNI.   -!\\!/~-.....  .ZWD@@x    !NSa}virJu}crt?cJO6.    .........................  i@Lcvv[onIv|\tZP;    |WWNDWDNQQDRRRQ@NMMMMMMMMMMMMMMMMMMMMM
MMMMMMM%@RDD@@NXfiiiiiiiivb@Z|   ."\\!/~....    TQD@@u     ;UP/:-```'''':iPo`    ..........................   [El,..```..\Pn,     |QWNDKD@QQDRRRQNDMMMMMMMMMMMMMMMMMMMMM
MMMMMMMZORDD@@@%}iiiiiiiiii[Z&$|.  .':__.       [QR@@6      .qO[/;___;"inm]    ..............................  ~PUx|""\jT$\...... .%WNDWDDQWRRDDWNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMM%ZDDD@D@WK8ziiiiiiiiiioOW%a;  "2,        "NDR&E'  ...`;r}xe}][[[}[i_`....................................:rjjjjjlt"_:,'... .PWNRW@KQRKDDDW@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMOCR@@@@@QWD@p[iiiiiiiiirL@WKEZWML\!_.    .CDKKD/  .`-,:::::::::::,,:::,`...............................`----,:::::_____-.. !KWNDK@WW@WR@RD@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMM&TD@@NNKQRD@@@TliiiiiiiiicdDQQQMMMMM@Fui. jDKRRc  .`-::____;;;;_;____:,`...............................',::__;;;;;;;___`. .YQ&NRR@Q@NKWDR@@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMQLNNNNNQWDDDDDW@hjiiiiiiiii[PRKWQQMQWXn/  -EWD@n  ..`,::____________:,`................................`-,:_________:,`. .nQQWNRD@QNNRWRD@@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM5%NNNWQDRRRRWWWQNqariiiiiiiijCDWWQm%m&MNo;LW&@P'  ...`',::::::,,--'`................................................  .[NMMMMRD@W@XNDDW@N@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMugNN@MKRRRRKWQWQNZZ$nliiiiiiii[SWQm%ZZXWMQ@QK@X|     ....`...................':_;"""""""~~~~~~~~/\||iii|||\\!!!!!!\|ijU@R&DDR@NDWXO@@@W@N@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMuT@NQQDRRR&WQQQWO%%ZN@h[iiiiiiiieZRm%%%%DQ%NW&@%f~.     .......:__:________________:::,'`.............................`,_;"\ivznZ%XN@@WDNNQMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM5nNRQKRRRRWWWQQKX%%%OQ&DSIiiiiiiii5mDOE%%NQQQWKWNNmCu?_      `~;,```'-,:::::::::,,,-----------''-'```````..................... :n%XO@@&WNNQMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMnuNQQRRRR&WWWQQRmEEEOQWWW@Zuriiiiiit5X@X%%ERMQWDuvvL%mmqnfi"\\`:____:::::::::,,,,,--------''```````````.......................;nZmOONDRQ@@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMn5@QRRRR&KWWWQQDmmmEOQQWR@@@ELliiiiiir5m@m%%@QQQmnZmFTLd%@EXL_______::::::::,,,,-----''''```````````.........................;gZEOOONDKQ&@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMLLWKRR&KKWWWWWQDmmmmOQQWD@@@@@Xwziiiiiir5E@mZ@QQQXZZZPP@@ZCh"______::::::,,,,,-,----'`````````````.........................._ZN%XONNO@WQQ@QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMQTZQRRRKKKWWWWWQ@mmmmXQQKDDDDD@@@OPftiiiiitoPNDKQWD8TC%EknLZ\_____:::::,,,,,,,------''``````````............................:YWDmNNNNNNRQQ&QMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMPKWRRR&KKWWWWWQ@XXXmXQQRDDDDDD@@NDQ%uriiiiii}6FWQQW@nynLzot_____:::::,,,,--------'''`````.................................`n@QWNNNNNNN@QQQMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWQRRRRRRKWDWWWQ@XXXXXWQD@DDD@@@@@DMWRm2siiiiiivFQQ@ET55yLj_____::::,,-----------'''`````..................................[ORQQNNNNNNNNWQQMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMQRRRRRRKWK@RWWQ@XOOXXWQD@@@@@@@@@@MQWNZPL}tiiaqTI|:..."Ou_____:::,,----------''`````.....................................\%NWMM@NNNNNNODQQMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWRRRRR&WQW@DQQQ@OOOOXWQD@@@@@@@@@@MMQmZZZ%Zd%L_.......[n__::::::,---''-''''''```........................................;UNDWQMQDDDD@@@DQQMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWRR&RRWQQQ&RQQQDOONOOQQDNNNNNNNNNNMMD%%%ZZZmn........\P;::::::,,--''''''```````.........................................yPZZPPPZZ%%mXN@DQQMMMMMMMMMMMMMMMMMMMMMM
@&QMMMQONOZSmWQWWQQWK&K&DRRRRQMKNNNNNNNNNNQMOmEE%ZPP~......._gf::::::,,-''``````````...........................................igPOXXXXXXmE%UwLq@QMMMMMMMMMMMMMMMMMMMMMM
";!uQDNNX%ZSX@mN@DWWN%TfxouLbPE%ZXNXONNNNNQWmmmEEEPb'......`LL::,:,,,-'`````````..............................................:LZnYmmmmmXXXXwoTLNQMMMMMMMMMMMMMMMMMMMMMM
Cx~!NZSEXNDQQXSZ@N@RWX%SIj[[[[li\|TNNOONNNWKXXmEE%%%;......j8",,,,,-'```....................................................:;x%NDNEmXXXmmmm6uZ6%QMMMMMMMMMMMMMMMMMMMMMM
%%PTNSL$%XON&XP8Z@N@D&N%%n]z]j?i||!IN@ONNN&KXXXmEZ$qo:....~Pt'-,---``...................................................;!?ujeZZPXDOEmmmmmmmqnED@NOONN@DDDDDDDDDRRWWQMMM
WNPUPS5nZXXX@%ZPUZNO@@R@%%Y]?tiiii|!iF@NNNRWOXXXEPPSSCj:.`Tu'''-'``..................................................!xyjITZ8PPSgLm@mmmmmmmmZ%X%ZKQQQQQWWKRD@@@@NNNN@MMM
X@NPhZLo8NDD%PZZZPZNX@@@DEZPf|||iii||i2N@NKWNONOZZPPSUSYvuY_`''````................................................inJ"..J[$PPPPFnm@O%EmmmmXE8L5u@QQQMMMMMMMMMMMMMMMMMMM
mNN@@OSFNR&K@%USZZZZO%N@NDNPSo|\|||ivjcfZRWW@NNZZZPPPPSUSZi``````................................................:uu_ .._bSZZPPPPY8%NSmmXXXXZLTLn@QQQMMMMMMMMMMMMMMMMMMM
D@@@@XEmO@RRWW@S8PZ%%XZmNON@PF6|\\|t[[jl?oQD%ZZZZZZZPPPPSo'`'````................................................a5. ...|pPPPPPPPPSCphP%XXXXPLq@NNNNONN@@@@@@D&KWQQQQQMM
*/

#include <iostream>
#include <vector>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <utility>
#include <algorithm>
#include <climits>
#include <cstdio>
#include <cstring>
#include <cmath>
using namespace std;

#define ll long long
#define pii pair<int, int>

const int MOD = 1000000007;

inline ll p(ll x, ll y) {
  x %= MOD;
  ll ans = 1;
  while (y) {
    if (y & 1) ans = ans * x % MOD;
    x = x * x % MOD;
    y >>= 1;
  }
  return ans;
}

inline ll inv(ll x) {
  return p(x, MOD - 2);
}

// Solves one testcase:
inline void solve() {

}

int main() {
  ios_base::sync_with_stdio(false); cin.tie(NULL);
  int t = 1;
  cin >> t;
  for (int i = 0; i < t; ++i) solve();
  return 0;
}
